sudo: false
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
language: ruby  
rvm:
  - "2.2.0"
services:
  - mongodb
addons:
  code_climate:
    repo_token: c753880c164fec791d3a7b74aff910830ada4b87e7b03d1ce9ce74bebaaa2098
script:
  - cd dummy
  - ln -s ../.git .git
  - cp config/database.travis.yml config/database.yml
  - RAILS_ENV=test bundle exec rake db:create
  - bundle exec rake db:test:prepare
  - CODECLIMATE_REPO_TOKEN=c753880c164fec791d3a7b74aff910830ada4b87e7b03d1ce9ce74bebaaa2098 bundle exec rspec
